const data = {
    products: [
        {
            name: 'Zara Slim dress',
            slug:'Zara-slim-shirt',
            category:'Adresse',
            image:'images/models5.jpg',
            price:1820,
            Stock: 10,
            brand:'Zara',
            rating:4.5,
            RewiesNumber:10,
            description:'high quality',
        },
        {
            name: 'massimo dutti dress',
            slug:'massimo dutti-slim-shirt',
            category:'Shirts',
            image:'images/models.jpg',
            price:2000,
            Stock: 30,
            brand:'massimo dutti',
            rating:2.5,
            RewiesNumber:12,
            description:'high quality',
        },
        {
            name: 'Zara jacket',
            slug:' jacket',
            category:'Shirts',
            image:'images/mm.jpg',
            price:1250,
            Stock: 15,
            brand:'Zara ',
            rating:3.2,
            RewiesNumber:17,
            description:'high quality',
        },
        {
            name: 'louis vuitton dress',
            slug:'dresses',
            category:'Shirts',
            image:'images/modelsa.jpg',
            price:1200,
            Stock: 15,
            brand:'Adidas',
            rating:3.2,
            RewiesNumber:17,
            description:'high quality',
        },
        {
            name: 'louis vuitton',
            slug:'louis jacket',
            category:'Shirts',
            image:'images/modelss.jpg',
            price:1500 ,
            Stock: 15,
            brand:'Adidas',
            rating:3.2,
            RewiesNumber:17,
            description:'high quality',
        },
        {
            name: 'louis vuitton dress',
            slug:'louis dress',
            category:'dresses',
            image:'images/ww.jpg',
            price:150,
            Stock: 15,
            brand:'louis vuitton ',
            rating:3.2,
            RewiesNumber:17,
            description:'high quality',
        },
        {
            name: 'bershka. Slim shirt',
            slug:'shirt',
            category:'Shirts',
            image:'images/n4.jpg',
            price:150,
            Stock: 15,
            brand:'bershka.',
            rating:3.2,
            RewiesNumber:17,
            description:'high quality',
        },
        {
            name: 'Prada',
            slug:'Pradashirt',
            category:'Shirts',
            image:'images/models1.jpg',
            price:150,
            Stock: 15,
            brand:'Adidas',
            rating:3.2,
            RewiesNumber:17,
            description:'high quality',
        },
        {
            name: 'Tomi',
            slug:'Tomi-shirt',
            category:'Shirts',
            image:'images/fam.jpg',
            price:130,
            Stock: 15,
        },
        {
            name: 'Zara jacket',
            slug:'Zara linen',
            category:'Shirts',
            image:'images/re.jpg',
            price:240,
            Stock: 15,
            brand:'Zara ',
            rating:3.2,
            RewiesNumber:17,
            description:'high quality',
        },
        {
            name: 'Zara jacket',
            slug:'Zara-shorts',
            category:'Shirts',
            image:'images/gf.jpg',
            price:750,
            Stock: 15,
            brand:'Zara ',
            rating:3.2,
            RewiesNumber:17,
            description:'high quality',
        },
        {
            name: 'Zara short',
            slug:'Zara pants',
            category:'Shirts',
            image:'images/ya.jpg',
            price:250,
            Stock: 15,
            brand:'Zara ',
            rating:3.2,
            RewiesNumber:17,
            description:'high quality',
        },
       
    ],
};


export default data;