const data = {
    products: [
        {
            name: 'Zara Slim dress',
            slug:'Zara-slim-shirt',
            category:'Adresse',
            image:'/images/models5.jpg',
            price:1820,
            countInStock: 10,
            countInStock: 0,
            brand:'Zara',
            rating:4.5,
            numReviews: 10,
            description:'high quality product',
        },
        {
            name: 'massimo dutti dress',
            slug:'massimo dutti-slim-shirt',
            category:'Shirts',
            image:'/images/models.jpg',
            price:2000,
            countInStock: 30,
            countInStock: 0,
            brand:'massimo dutti',
            rating:2.5,
            numReviews:12,
            description:'high quality',
        },
        {
            name: 'Zara jacket',
            slug:' jacket',
            category:'Shirts',
            image:'/images/mm.jpg',
            price:1250,
            countInStock: 0,
            countInStock: 0,
            brand:'Zara ',
            rating:3.2,
            numReviews:17,
            description:'high quality',
        },
        {
            name: 'louis vuitton dress',
            slug:'dresses',
            category:'Shirts',
            image:'/images/modelsa.jpg',
            price:1200,
            countInStock: 12,
            countInStock: 0,
            brand:'Adidas',
            rating:3.2,
            numReviews:10,
            description:'high quality',
        },
        {
            name: 'louis vuitton',
            slug:'louis jacket',
            category:'Shirts',
            image:'/images/modelss.jpg',
            price:1500 ,
            countInStock: 9,
            countInStock: 0,
            brand:'Adidas',
            rating:3.2,
            numReviews:13,
            description:'high quality',
        },
        {
            name: 'louis vuitton dress',
            slug:'louis dress',
            category:'dresses',
            image:'/images/ww.jpg',
            price:150,
            countInStock: 11,
            countInStock: 0,
            brand:'louis vuitton ',
            rating:3.2,
            numReviews:17,
            description:'high quality',
        },
        {
            name: 'bershka. Slim shirt',
            slug:'shirt',
            category:'Shirts',
            image:'/images/n4.jpg',
            price:150,
            countInStock: 15,
            countInStock: 0,
            brand:'bershka.',
            rating:3.2,
            numReviews:22,
            description:'high quality',
        },
        {
            name: 'Prada',
            slug:'Pradashirt',
            category:'Shirts',
            image:'/images/models1.jpg',
            price:150,
            countInStock: 12,
            countInStock: 0,
            brand:'Adidas',
            rating:3.2,
            numReviews:19,
            description:'high quality',
        },
        {
            name: 'Tomi',
            slug:'Tomi-shirt',
            category:'Shirts',
            image:'/images/fam.jpg',
            price:130,
            countInStock: 10,
            countInStock: 0,
            brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
        },
        {
            name: 'Zara jacket',
            slug:'Zara linen',
            category:'Shirts',
            image:'/images/re.jpg',
            price:240,
            Stock: 15,
            brand:'Zara ',
            rating:3.2,
            numReviews:17,
            description:'high quality',
        },
        {
            name: 'Zara jacket',
            slug:'Zara-shorts',
            category:'Shirts',
            image:'/images/gf.jpg',
            price:750,
            Stock: 15,
            brand:'Zara ',
            rating:3.2,
            numReviews:11,
            description:'high quality',
        },
        {
            name: 'Zara short',
            slug:'Zara pants',
            category:'Shirts',
            image:'/images/ya.jpg',
            price:250,
            Stock: 15,
            brand:'Zara ',
            rating:3.2,
            numReviews:15,
            description:'high quality',
        },
       
    ],
};


export default data;